version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: futbol_app_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./futbol-app-backend
    container_name: futbol-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/futbol_app_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    restart: on-failure

  frontend:
    build:
      context: ./futbol-app-frontend
      dockerfile: Dockerfile
    container_name: futbol-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: on-failure

volumes:
  db_data: