
services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-futbol_app_db}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./futbol-app-backend
    container_name: futbol-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB:-futbol_app_db}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-admin}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    restart: on-failure

  frontend:
    build:
      context: ./futbol-app-frontend
      dockerfile: Dockerfile
    container_name: futbol-frontend
    ports:
      - "${FRONTEND_PORT:-4200}:80"
    depends_on:
      - backend
    restart: on-failure

volumes:
  db_data: